# Generated by Django 6.0.4 on 2026-05-12 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'status'},
        ),
        migrations.RenameField(
            model_name='status',
            old_name='descrition',
            new_name='description',
        ),
    ]
