# Generated by Django 6.0.4 on 2026-05-12 02:12

from django.db import migrations


def populate_status(apps, schemaeditor):
    entries = {
        "published":"A post aveilable for all to view",
        "draft": "A post only visible only to the author",
        "archived":"an older post visible only to the logged user"
    }
     
    Status = apps.get_model("posts", "Status",)
    for key, value in entries.items():
        status_obj = Status(name=key, description=value)
        status_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_status_options_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_status)
    ]
