# Generated by Django 6.0.4 on 2026-05-14 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Status',
            new_name='status',
        ),
    ]
